title: Maranda's Blog Demo
author: Maranda Nieman
email: maranda.nieman@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Maranda Nieman's Github Blog tutorial.

# social links
github_username:  MarandaNieman

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
